# Generated by Django 2.2.4 on 2020-06-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('livro', 'Livro'), ('cd', 'CD'), ('vinil', 'Vinil'), ('mp3', 'MP3'), ('mp4', 'MP4'), ('filme', 'Filme'), ('dvd', 'DVD'), ('blu-ray', 'Blu-Ray')], max_length=50, verbose_name='tipo do arquivo')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fisica', 'Fisica'), ('digital', 'Digital')], max_length=50, verbose_name='tipo da midia')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='C:\\uploader/app/static/files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emprestado', models.BooleanField(blank=True, null=True)),
                ('emprestado_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emprestado_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('size', models.FloatField()),
                ('old_name', models.CharField(max_length=150)),
                ('tipo_de_arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Arquivo', verbose_name='tipo de arquivo')),
                ('tipo_de_midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Midia', verbose_name='tipo de midia')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
